"""Se agrega relacion de turnos con pacientes

Revision ID: 1aef758f7985
Revises: 6aed5a947322
Create Date: 2024-06-18 15:45:05.788399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1aef758f7985'
down_revision = '6aed5a947322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('obra_soc', sa.String(length=30), nullable=True))
        batch_op.drop_constraint('usuarios_ibfk_1', type_='foreignkey')
        batch_op.drop_column('id_paciente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_paciente', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('usuarios_ibfk_1', 'pacientes', ['id_paciente'], ['id_paciente'])
        batch_op.drop_column('obra_soc')

    # ### end Alembic commands ###
