"""Se crean las tablas pacientes, turnos y usuarios correctamente

Revision ID: 4469d089f480
Revises: eafad3ceb842
Create Date: 2024-06-04 21:43:03.888350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4469d089f480'
down_revision = 'eafad3ceb842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id_paciente', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.Integer(), nullable=False),
    sa.Column('fecha_nac', sa.Date(), nullable=False),
    sa.Column('obra_soc', sa.String(length=30), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('direccion', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    op.create_table('turnos',
    sa.Column('id_turno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_turno')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_usuario', sa.String(length=30), nullable=False),
    sa.Column('contraseña', sa.String(length=8), nullable=False),
    sa.Column('rol', sa.Enum('secretaria', 'cliente'), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_paciente'], ['pacientes.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('turnos')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
