"""se agrega rol facturista

Revision ID: a17df46d0f03
Revises: 5d32ee88477d
Create Date: 2024-06-24 18:03:02.800780

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a17df46d0f03'
down_revision = '5d32ee88477d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=mysql.ENUM('secretaria', 'cliente', 'facturista'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('rol',
               existing_type=mysql.ENUM('secretaria', 'cliente', 'facturista'),
               nullable=True)

    # ### end Alembic commands ###
